# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('pub_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Publication date')),
                ('content', models.TextField(verbose_name='Content')),
                ('setka_theme_id', models.CharField(max_length=255)),
                ('setla_layout_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('alt', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SetkaDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dump', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetkaPublished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('dump', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='setka_editor.Article')),
            ],
            bases=('setka_editor.article',),
        ),
        migrations.AddField(
            model_name='setkapublished',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setka_editor.AdvancedArticle'),
        ),
        migrations.AddField(
            model_name='setkadraft',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setka_editor.AdvancedArticle'),
        ),
    ]
